# Change these first
owner: Primitives-xyz # Your GitHub organization or username, where this repository lives
repo: prim-monitor # The name of this repository

sites:
  - name: Quicknode
    url: ${{ secrets.QUICKNODEURL }}


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /prim-monitor
  logoUrl: https://mma.prnewswire.com/media/1821198/Primitives_Logo.jpg?p=facebook
  name: Primitives Status Page ⚡️
  introTitle: "We will use this page to track all things Primitives!."
  introMessage: If you want to add a tracker, add a ticket!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
